version: '3.9'

services:
  website:
    entrypoint: flask run -h 0.0.0.0
    env_file:
      - .env-dev
    volumes:
      - ./app:/app

  mongo:
    env_file:
      - .env-dev

  mongo-express:
    image: mongo-express
    env_file:
      - .env-dev
    ports:
      - '8081:8081'
    depends_on:
      - mongo
    restart: unless-stopped