version: '3.9'

services:
  website:
    build:
      context: .
    env_file:
      - .env-prod
    ports:
      - '5000:5000'

  mongo:
    image: mongo
    env_file:
      - .env-prod
    ports:
      - '27017:27017'